CREATE DATABASE EMPRESA

CREATE TABLE PERSONA (
IDPERSONA INT IDENTITY (1,1) NOT NULL,
NOMBRE NVARCHAR (50) NOT NULL,
APELLIDO NVARCHAR (50) NOT NULL,
ESTADO NVARCHAR (20) NOT NULL,
PRIMARY KEY (IDPERSONA),
);
CREATE TABLE EMPLEADO (
IDEMPLEADO INT IDENTITY (1,1) NOT NULL,
IDPERSONA INT NOT NULL,
PUESTO NVARCHAR (50) NULL,
SALARIO MONEY NOT NULL,
FECHA_CONTRATACION DATETIME NOT NULL,
PRIMARY KEY (IDEMPLEADO),
FOREIGN KEY (IDPERSONA) REFERENCES PERSONA (IDPERSONA)
);

insert into PERSONA values('Pedro' ,'Fernandez' , ,'Activo');
insert into PERSONA values('Adrián' ,'Pérez' ,'Activo');
insert into PERSONA values('Belén' ,'González' ,'Activo');
insert into PERSONA values('Ana' ,'Rodríguez' ,'Inactivo');
insert into PERSONA values('Bruno' ,'López' ,'Activo');

SELECT * FROM PERSONA

insert into EMPLEADO values (1, 'GERENTE',20000, '2022-02-01 14:00:00');
SELECT * FROM EMPLEADO